### ISSUE TITLE
Paginated results

### ISSUE THREAD

**Issue by thujohn** [alaouy/Youtube#16]
Hi.

I'm trying  to make a part in my website with paginated results.

```Youtube::getPlaylistItemsByPlaylistId('xxxxxx')``` returns only 50 results but what I want is only 8 results and the ability to change the page.

```php
getPlaylistItemsByPlaylistId($playlistId, $pageToken = false, $maxResults = 50, $part = ['id', 'snippet', 'contentDetails', 'status'])
```
What is $pageToken ?

Thank you

**Comment by thujohn** [comment]
With ```Youtube::getPlaylistItemsByPlaylistId('xxxxxx', true)``` I get results and infos.

I don't know if it is the best method but it works.

Is there a way to get all the pagination ?

**Comment by alaouy** [comment]
Hi @thujohn,
Yes you can paginate your playlist per 8 items like this
```php
$items = Youtube::getPlaylistItemsByPlaylistId('xxxxxx', true, 8);
```
This will give you the results array plus the info array which contains the pagetokens that you can use to query next/prev pages like this
```php
// First page
$items1 = Youtube::getPlaylistItemsByPlaylistId('xxxxxx', true, 8);

// Second page
$items2 = Youtube::getPlaylistItemsByPlaylistId('xxxxxx', $items1['info']['nextPageToken'], 8);

```
Unfortunately Youtube does not provide a way to get all the pagetokens at once, you'll have to query them in the first time and **cache** it, so that you don't exceed your API quota.

**Comment by mverma16** [comment]
Works for me thanks @thujohn
