### ISSUE TITLE
Abandon support for Laravel 4

### ISSUE THREAD

**Issue by bzbislawski** [alaouy/Youtube#58]
@alaouy 
What is the aim of this repo? I think this package should stop supporting deprecated software and tools. Reasons:
- Zend is not supporting PHP 5.3 anymore,
- Laravel 4 is not supported anymore
- many more...

What I suggest is creating two branches. One for PHP 7 and Laravel 5.* and the other branch for current old package which still supports old stuff.

Thoughts?

B

**Comment by alaouy** [comment]
@bzbislawski Thanks for you contribution, I completely agree with your proposal, will cleanup the code and put it in the appropriate branches, do you have any features that you want to see in this packages in the future ?

**Comment by geoSo** [comment]
Hello, as I saw, the above question, i would like to suggest you, for Laraver 5.* to  keep the support for php 5.5 and above, cause many servers are still working on these versions.

As of the package I haven't use it yet, so I am not sure about all its capabilities.
I think  an "**exists**" method _(returns bool)_ would be great in order to be sure that a video exists before we proceed with it 

For example: `$video = Youtube::getVideoInfo('rie-hPVJ7Sw');
$video->exists();`

Also as a major update you could try to extend the package, in order to be able to Upload videos or even playlists to a user Account. It would be a competed approach without the need of other packages

**Comment by alaouy** [comment]
Laravel 4.* and Php5 support are now under the `php5` branch.
