### ISSUE TITLE
How to refresh the api key ?

### ISSUE THREAD

**Issue by ahmedsliman** [alaouy/Youtube#7]
I use an api key generated from google console but it expires every 24 hours, How can i make it valid for ever or for long time ?

Thanks

**Comment by alaouy** [comment]
The api key does not change unless you manualy generate it from the console, So I guess your problem is not related to the api key, but to the IP adress that you set in the credentials section of your app, your IP adress changes every day (depending on your ISP) that's why you can't access the app the next day, my recommendation is to leave the Allowed IPS section empty, that way any IP you'll use with api key will be allowed. I hope this helps you.

**Comment by ahmedsliman** [comment]
Thanks for reply,

But when i try to generate a new api in google it said:

"Do you want to replace the current key with a new one?
The new key will be available immediately. The current key will be deactivated permanently in 24 hours."

So i guess it doesn't related with IPS

Thanks

**Comment by alaouy** [comment]
@ahmedsliman No, you don't need to generate a key everytime, you do it only ***once*** and you use the same api key for your app.
